### ISSUE TITLE
Error after Installation

### ISSUE THREAD

**Issue by tlford82** [SaintsSec/Navi#109]
![navi-error](https://github.com/user-attachments/assets/39a90570-6834-4544-a5a9-e71c8024d37b)
While installing Navi 0.6.5 this error is generated at the end of the installation process.  Most likely related to a previously generated alias in bashrc.

**Comment by AlexKollar** [comment]
There is that but let me run through install and see whats up.

**Comment by AlexKollar** [comment]
This issue is currently going into pending status. If anyone else runs into this drop a screenshot.... As of right now its not showing up on either my local install or my CSI Linux install.
