### ISSUE TITLE
Recon Automation Expansion

### ISSUE THREAD

**Issue by AlexKollar** [SaintsSec/Navi#3]
### As of right now:  
We have nmap automation done and accounted for. 
As well as the ability to save a custom file for later report viewing. 

### To be added: 
- [x] Ping Scans
- [x] Whois
- [ ] Nessus
- [ ] Nuclei
- [ ] Nikito
- [ ] Shodan
- [ ] Split up into functions

If anyone has any other ideas please do drop them here!

**Comment by RahulDubey391** [comment]
Hi @AlexKollar , @marvhus , I hope you are doing well. I went through the codebase, functionality & goal of the project. I must say it aligns with my interest and would like to start contributing to improve the project. I would be really happy if you can assign this issue to me. But at the same time I'll require your guidance and mentorship to show me correct path. Thanks!!!

**Comment by AlexKollar** [comment]
@RahulDubey391 Welcome. I am glad that you find the project interesting. 
I just got done adding whois to the recon automation code. I'm pleased to say it works. 

I think here soon we will need to start adding methods to the various recon bits instead of one long line of them. That and I will need to go in and properly comment that code so it makes more sense. 

In the meantime, you are more than welcome to join our community discord and come chat.
