### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by tlford82** [SaintsSec/Navi#73]
When installing the current version of Navi I've encountered several errors. Attached are screenshots of the install and attempted execution of Navi from the command-line. This install was attempted on a vanilla Ubuntu 22.04 install.  First screenshot shows the attempted execution of python3 navi_shell.py --Install 
![image](https://github.com/SaintsSec/Navi/assets/111040187/e32d6cc5-e95f-4642-87c8-0b3b37b96321)

Running the install via the included script seems to install Navi properly but still leaves it in an un-executable state. 
![image](https://github.com/SaintsSec/Navi/assets/111040187/9ca2d63c-406d-49b4-a72c-a1b5ae3314ce)
![image](https://github.com/SaintsSec/Navi/assets/111040187/124ca1f1-97f7-405f-ac75-63bb0c72f4b3)

**Comment by AlexKollar** [comment]
This should be patched now.

**Comment by tlford82** [comment]
Patched and working perfectly, Alex!
